Config File: /home/none/.config/solana/cli/config.yml
RPC URL: https://api.devnet.solana.com 
WebSocket URL: wss://api.devnet.solana.com/ (computed)
Keypair Path: gibbwebMtnpXiYieNQPg3zuk8vATH1JY1c4pbJuidza.json 
Commitment: confirmed 
